[Distribution]
Distribution=debian
Release=trixie

[Build]
WithNetwork=true
Environment=GAIKO2_BIN TAIKO_GETH_BIN TAIKO_CLIENT_BIN TDXS_BIN

[Output]
Format=uki
ManifestFormat=json
Output=tdx-gaiko2

[Content]
SourceDateEpoch=0
KernelCommandLine=console=tty0 console=ttyS0,115200n8 mitigations=auto,nosmt spec_store_bypass_disable=on
ExtraTrees=mkosi.extra
BuildScripts=mkosi.build
PostInstallationScripts=mkosi.postinst
CleanPackageMetadata=true
Packages=
    ca-certificates
    curl
    iproute2
    jq
    kmod
    openssl
    procps
    systemd
    systemd-boot-efi
    util-linux
